name: Type Check
on: [push, pull_request]
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Run mypy
        run: uv run --locked --all-extras mypy src
